apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
  #values required for daws78s
data:
  DB_HOST: mysql # mysql component service name

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
  # below is pod definition. pod is subset of replicaset   
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: app
    spec:
      containers:
      - name: backend
        image: leelakamineni/backend:v1.0
        envFrom:
        - configMapRef:
            name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: app
  ports:
  - protocol: TCP
    port: 8080 # service-port
    targetPort: 8080  #target-port       

